USE homecreditloans;
CREATE TABLE previous_application (
sk_id_prev  int not null, 
sk_id_curr int not null, 
name_contract_type varchar(20) not null, 
amt_annuity varchar(20) null, 
amt_application decimal(15,3) not null, 
amt_credit decimal(15,3) not null, 
amt_down_payment varchar(20) null, 
amt_goods_price varchar(20) null, 
weekday_appr_process_start varchar(10) not null, 
hour_appr_process_start tinyint not null, 
flag_last_appl_per_contract varchar(5) not null, 
nflag_last_appl_in_day tinyint not null, 
rate_down_payment varchar(20) null, 
rate_interest_primary varchar(20) null, 
rate_interest_privileged varchar(20) null, 
name_cash_loan_purpose varchar(40) not null, 
name_contract_status varchar(20) not null, 
days_decision mediumint not null, 
name_payment_type varchar(50) not null, 
code_reject_reason varchar(10) not null, 
name_type_suite varchar(20) null, 
name_client_type varchar(10) not null, 
name_goods_category varchar(30) not null, 
name_portfolio varchar(10) not null, 
name_product_type varchar(10) not null, 
channel_type varchar(30) not null, 
sellerplace_area mediumint not null, 
name_seller_industry varchar(20) not null, 
cnt_payment varchar(5) null, 
name_yield_group varchar(10) not null, 
product_combination varchar(30) null, 
days_first_drawing varchar(10) null, 
days_first_due varchar(10) null, 
days_last_due_1st_version varchar(10) null, 
days_last_due varchar(10) null, 
days_termination varchar(10) null, 
nflag_insured_on_approval varchar(5) null);
ALTER TABLE previous_application ADD CONSTRAINT previous_application_PK PRIMARY KEY (sk_id_prev);
CREATE INDEX previous_application_INDX ON previous_application (sk_id_curr);
ALTER TABLE previous_application ADD CONSTRAINT previous_application_FK FOREIGN KEY (sk_id_curr) REFERENCES application (sk_id_curr);

CREATE TABLE previous_application_raw1 (
sk_id_prev  int not null, 
sk_id_curr int not null, 
name_contract_type varchar(20) not null, 
amt_annuity varchar(20) null, 
amt_application decimal(15,3) not null, 
amt_credit decimal(15,3) not null, 
amt_down_payment varchar(20) null, 
amt_goods_price varchar(20) null, 
weekday_appr_process_start varchar(10) not null, 
hour_appr_process_start tinyint not null, 
flag_last_appl_per_contract varchar(5) not null, 
nflag_last_appl_in_day tinyint not null, 
rate_down_payment varchar(20) null, 
rate_interest_primary varchar(20) null, 
rate_interest_privileged varchar(20) null, 
name_cash_loan_purpose varchar(40) not null, 
name_contract_status varchar(20) not null, 
days_decision mediumint not null, 
name_payment_type varchar(50) not null, 
code_reject_reason varchar(10) not null, 
name_type_suite varchar(20) null, 
name_client_type varchar(10) not null, 
name_goods_category varchar(30) not null, 
name_portfolio varchar(10) not null, 
name_product_type varchar(10) not null, 
channel_type varchar(30) not null, 
sellerplace_area mediumint not null, 
name_seller_industry varchar(20) not null, 
cnt_payment varchar(5) null, 
name_yield_group varchar(10) not null, 
product_combination varchar(30) null, 
days_first_drawing varchar(10) null, 
days_first_due varchar(10) null, 
days_last_due_1st_version varchar(10) null, 
days_last_due varchar(10) null, 
days_termination varchar(10) null, 
nflag_insured_on_approval varchar(5) null);
CREATE TABLE previous_application_raw2 (
sk_id_prev  int not null, 
sk_id_curr int not null, 
name_contract_type varchar(20) not null, 
amt_annuity varchar(20) null, 
amt_application decimal(15,3) not null, 
amt_credit decimal(15,3) not null, 
amt_down_payment varchar(20) null, 
amt_goods_price varchar(20) null, 
weekday_appr_process_start varchar(10) not null, 
hour_appr_process_start tinyint not null, 
flag_last_appl_per_contract varchar(5) not null, 
nflag_last_appl_in_day tinyint not null, 
rate_down_payment varchar(20) null, 
rate_interest_primary varchar(20) null, 
rate_interest_privileged varchar(20) null, 
name_cash_loan_purpose varchar(40) not null, 
name_contract_status varchar(20) not null, 
days_decision mediumint not null, 
name_payment_type varchar(50) not null, 
code_reject_reason varchar(10) not null, 
name_type_suite varchar(20) null, 
name_client_type varchar(10) not null, 
name_goods_category varchar(30) not null, 
name_portfolio varchar(10) not null, 
name_product_type varchar(10) not null, 
channel_type varchar(30) not null, 
sellerplace_area mediumint not null, 
name_seller_industry varchar(20) not null, 
cnt_payment varchar(5) null, 
name_yield_group varchar(10) not null, 
product_combination varchar(30) null, 
days_first_drawing varchar(10) null, 
days_first_due varchar(10) null, 
days_last_due_1st_version varchar(10) null, 
days_last_due varchar(10) null, 
days_termination varchar(10) null, 
nflag_insured_on_approval varchar(5) null);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/previous_application_chunk1.csv' INTO TABLE previous_application_raw1 
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;
LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/previous_application_chunk2.csv' INTO TABLE previous_application_raw2 
FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' IGNORE 1 LINES;

CREATE TABLE master_previous_application AS (SELECT * FROM previous_application_raw1 UNION SELECT * FROM previous_application_raw2);
DROP TABLE IF EXISTS previous_application_raw1;
DROP TABLE IF EXISTS previous_application_raw2;

INSERT INTO previous_application SELECT * FROM master_previous_application;
DROP TABLE IF EXISTS master_previous_application;
